language: python
services:
- docker
python:
- 3.6
dist: trusty
install:
- pip install --force-reinstall --upgrade -r REQUIREMENTS-DEV.txt -r REQUIREMENTS-NOTEBOOK.txt
- pip install -e .
- pip freeze
script:
- export MPLBACKEND=Agg
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- case "$BRANCH" in
  master|merge)
    make slow
    ;;
  *)
    make fast
    ;;
  esac
after_success:
- bash <(curl -s https://codecov.io/bash)
