language: python
sudo: required
services:
- docker
python:
- 3.6
dist: trusty
install:
- pip install -r REQUIREMENTS-DEV.txt -r REQUIREMENTS-NOTEBOOK.txt
- pip install -e .
- pip freeze
- docker build -t spacetx/starfish .
script:
- export MPLBACKEND=Agg
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- set -eo pipefail
- make all
- if [ "$BRANCH" == "master" ]; then make run_notebooks; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
