name: starfish
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- python>=3.6
- click
- pandas>=0.23.4
- pytest>=3.6.3
- regional
- scikit-image>=0.14.0
- scikit-learn
- semantic_version
- showit==1.1.4
- slicedimage==0.0.2
- tqdm
- trackpy
- validators
- xarray
